// src/comp/Header.jsx
// ../comp/Header.jsx
import React from 'react';
import './header.css';

function Header() {
  return (
    <header className="header">
      <div className="header-content">
        <h1 className="site-title">GGLVXD.EU.ORG</h1>
        <nav className="navigation">
          <a href="/" className="nav-link">Home</a>
          <a href="https://status.gglvxd.eu.org" className="nav-link">Status</a>
          <a href="/skills" className="nav-link">Skills</a>
          <a href="/projects" className="nav-link">Projects</a>
          <a href="https://blog.gglvxd.eu.org" className="nav-link">Blog</a>
        </nav>
      </div>
    </header>
  );
}

export default Header;

// src/header/header.svelte
<script>
	let mobileMenuOpen = false;
  
	function toggleMenu() {
	  mobileMenuOpen = !mobileMenuOpen;
	}
  </script>
  
  <header class="header">
	<div class="logo">
	  <a href="/">GGLVXD.EU.ORG</a>
	</div>
	
	<button class="mobile-menu-btn" on:click={toggleMenu}>
	  <span>{mobileMenuOpen ? '✖' : '☰'}</span>
	</button>
  
	<nav class={`nav-links ${mobileMenuOpen ? 'open' : ''}`}>
	  <a href="/">Home</a>
	  <a href="/blog" target="_blank">Blog</a>
	  <a href="https://status.gglvxd.eu.org" target="_blank">Status</a>
	  <a href="https://github.com/gglvxd/website" target="_blank">Github</a>
	</nav>
  </header>
  
  <style>
	@import '../header/header.css';
  </style>
