// src/header/header.jsx
import React from 'react';
import './header.css';

function Header() {
  return (
    <header className="Header">
      <nav className="Nav">
        <div className="Logo">
          <h2>GGLVXD</h2>
        </div>
        <div className="NavLinks">
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="https://status.gglvxd.eu.org/">Status</a></li>
            <li><a href="https://dsc.gg/gglvxd">Discord</a></li>
          </ul>
        </div>
      </nav>
    </header>
  );
}

export default Header;

// src/header/header.svelte
<script>
	let mobileMenuOpen = false;
  
	function toggleMenu() {
	  mobileMenuOpen = !mobileMenuOpen;
	}
  </script>
  
  <header class="header">
	<div class="logo">
	  <a href="/">GGLVXD.EU.ORG</a>
	</div>
	
	<button class="mobile-menu-btn" on:click={toggleMenu}>
	  <span>{mobileMenuOpen ? '✖' : '☰'}</span>
	</button>
  
	<nav class={`nav-links ${mobileMenuOpen ? 'open' : ''}`}>
	  <a href="/">Home</a>
	  <a href="https://status.gglvxd.eu.org" target="_blank">Status</a>
	  <a href="https://github.com/gglvxd/website" target="_blank">Github</a>
	</nav>
  </header>
  
  <style>
	@import '../header/header.css';
  </style>
